### ISSUE TITLE
Styles that don't need RTL treatment are getting treated.

### ISSUE THREAD

**Issue by dzearing** [jakob101/postcss-inline-rtl#1]
.Foo {
  background: red;
}

Expected:
Should output unchanged.

Resulted:
html[dir=ltr] .Foo{background:red}
html[dir=rtl] .Foo{background:red}

**Comment by dzearing** [comment]
Nevermind! I stepped through the code and understand why. it should be background-color, rather than background which could be RTL sensitive. :)

**Comment by dzearing** [comment]
This applies to background-color as well.
..and border-color

**Comment by dzearing** [comment]
And position related things that are RTL friendly;

border: 0;
border: 10px;
padding: 0 10px;

It just ends up bloating the CSS. It would be nice for these things to be evaluated and reduced so that only RTL sensitive rules get processed.

**Comment by jakob101** [comment]
Yup, propsToAlwaysConvert is an edge case which get treated. Not a big fan of it, but haven't found a solution yet.
As for border-color, it can have 4 values, thus it's rtl sensitive.
Let's say you have this code:.class {    border: 4px 3px 2px 1px;}.class:last-child {    border: none;}
It generateshtml[dir='ltr'] .class {    border: 4px 3px 2px 1px;}
html[dir='rtl'] .class {    border: 4px 2px 3px 1px;}
.class:last-child {   border: none;}
Since the prefixed ones have higher specificity, the last child wouldn't have no borders, it would be ignored.
So i need to "match" their specificity by converting "cancelled" props as well (like border: none). 
This is a problem I am aware of, and I tried a couple of solutions, but haven't found a good one yet.
    _____________________________

**Comment by jakob101** [comment]
Should be optimized with the latest version.
